{"name": "Verify that user can login with valid credentials", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service C:\\Users\\Dell\\.cache\\selenium\\chromedriver\\win64\\119.0.6045.105\\chromedriver.exe unexpectedly exited. Status code was: 1\n\n", "trace": "  File \"C:\\Users\\Dell\\Desktop\\POMBDDSELENIUM\\venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Dell\\Desktop\\POMBDDSELENIUM\\venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login.py\", line 12, in step_impl\n    context.driver = webdriver.Firefox(options=options)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dell\\Desktop\\POMBDDSELENIUM\\venv\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 60, in __init__\n    self.service.start()\n  File \"C:\\Users\\Dell\\Desktop\\POMBDDSELENIUM\\venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 102, in start\n    self.assert_process_still_running()\n  File \"C:\\Users\\Dell\\Desktop\\POMBDDSELENIUM\\venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 115, in assert_process_still_running\n    raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")\n"}, "steps": [{"name": "Given : User can load the demo website", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service C:\\Users\\Dell\\.cache\\selenium\\chromedriver\\win64\\119.0.6045.105\\chromedriver.exe unexpectedly exited. Status code was: 1\n\n", "trace": "  File \"C:\\Users\\Dell\\Desktop\\POMBDDSELENIUM\\venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Dell\\Desktop\\POMBDDSELENIUM\\venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login.py\", line 12, in step_impl\n    context.driver = webdriver.Firefox(options=options)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dell\\Desktop\\POMBDDSELENIUM\\venv\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 60, in __init__\n    self.service.start()\n  File \"C:\\Users\\Dell\\Desktop\\POMBDDSELENIUM\\venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 102, in start\n    self.assert_process_still_running()\n  File \"C:\\Users\\Dell\\Desktop\\POMBDDSELENIUM\\venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 115, in assert_process_still_running\n    raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")\n"}, "start": 1702115470444, "stop": 1702115473582}, {"name": "When : Enter Username", "status": "skipped", "start": 1702115473583, "stop": 1702115473583}, {"name": "When : Enter Password", "status": "skipped", "start": 1702115473583, "stop": 1702115473583}, {"name": "When : Click Login Button", "status": "skipped", "start": 1702115473583, "stop": 1702115473583}, {"name": "Then : User should be logged in successfully", "status": "skipped", "start": 1702115473583, "stop": 1702115473583}], "start": 1702115470443, "stop": 1702115473583, "uuid": "396d7c85-d8ca-4434-b3d8-6b9fd8287699", "historyId": "e937f93c2d9ab0f86d816d28021c5655", "fullName": "OrangeHRM Login: Verify that user can login with valid credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "OrangeHRM Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}